### ISSUE TITLE
Getting Error in Identity Display Name 

### ISSUE THREAD

**Issue by bingo007** [p0wershe11/ProxyLogon#2]
Traceback (most recent call last):
  File "proxylog.py", line 380, in <module>
    main()
  File "proxylog.py", line 346, in main
    return runner(MAIL)
  File "proxylog.py", line 332, in runner
    return exp(mail.split('@')[0], sid)
  File "proxylog.py", line 241, in exp
    Log.info(f"OAB Name = f{identity['DisplayName']}")
TypeError: 'NoneType' object is not subscriptable

**Comment by 0xmaximus** [comment]
same
